class Election[T]
  def initialize: (ballots: Array[Array[T]] ballots, ranker: Ranker::Schulze[T]) -> void

  def elect: () -> Array[T]

  private

  attr_writer path_strengths (): Array[Array[T]]
  attr_accessor ballots (): Array[Array[T]]

  def candidates: () -> Array[T]
  def num_candidates: () -> Integer
  def num_ballots_preferring: (T, T) -> Integer
end
