class Election[T]
  def initialize: (ballots: Array[Array[T]] ballots, ?ranker: Ranker::Schulze[T]) -> Election[T]

  def elect: () -> void

  attr_reader winners (): Array[T]
  attr_reader ranking (): Array[T]

  private

  attr_reader ranker (): Ranker::Schulze[T]
end
